# Generated by Django 4.1.5 on 2023-01-08 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
